name: Sync Subtrees
on:
  push:
    branches: main
    tags: 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  subtrees:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        action: [node-version, setup-nodenv]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch full history to replay in subtree
          token: ${{secrets.BOT_TOKEN}} # persisted for subsequent git operations
      - run: |
          split_head=$(git subtree split --prefix ${{matrix.action}})
          git push $remote ${split_head:?}:${{github.ref}}
        env:
          remote: https://github.com/${{github.repository}}-${{matrix.action}}

  master:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - run: git push --force-with-lease origin HEAD:refs/heads/master
